package com.mcmoddev.communitymod.erdbeerbaerlp.iconmod;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;

import net.minecraft.client.Minecraft;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;

public class mod extends DummyModContainer{
	public mod(){
		super(new ModMetadata());
		ModMetadata data = getMetadata();
		data.autogenerated = false;
		data.modId = LoadingPlugin.MODID;
		data.name = LoadingPlugin.NAME;
		data.authorList.add("ErdbeerbaerLP");
		data.description = "Sets a custom icon and title for this mod";
		data.version = LoadingPlugin.VERSION;
		//data.url = "https://minecraft.curseforge.com/projects/discordrichpresence";
	}
	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		bus.register(this);
		return true;
	}
	@Subscribe
	public void modConstruction(FMLConstructionEvent evt){

	}
	@Subscribe
	public static void init(FMLInitializationEvent event){
	}
}
